steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/market-research-app:$SHORT_SHA', '-t', 'gcr.io/$PROJECT_ID/market-research-app:latest', '.']
  
  # Push the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '--all-tags', 'gcr.io/$PROJECT_ID/market-research-app']
  
  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - 'run'
    - 'deploy'
    - 'market-research-app'
    - '--image'
    - 'gcr.io/$PROJECT_ID/market-research-app:$SHORT_SHA'
    - '--region'
    - 'us-central1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--memory'
    - '2Gi'
    - '--cpu'
    - '2'
    - '--concurrency'
    - '80'
    - '--max-instances'
    - '10'
    - '--port'
    - '8080'
    - '--timeout'
    - '900'
    - '--set-env-vars'
    - 'LLM_MODEL=gpt-4,LLM_TEMPERATURE=0.7,LLM_MAX_TOKENS=2000'
    - '--update-secrets'
    - 'OPENAI_API_KEY=openai-api-key:latest,TAVILY_API_KEY=tavily-api-key:latest'

# Store the image for future reference
images:
  - 'gcr.io/$PROJECT_ID/market-research-app:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/market-research-app:latest'

# Optional: Set substitutions for build variables
substitutions:
  _SERVICE_NAME: 'market-research-app'
  _REGION: 'us-central1'